load("@eros_forge//bazel:cmake_forge.bzl", "cmake_forge")

filegroup(
    name = "src_files",
    srcs = glob(["*.cpp", "CMakeLists.txt"]),
    visibility = ["//visibility:private"],
)

cmake_forge(
    name = "hello_world_cmake",
    lib_source = ":src_files",
    out_binaries = ["hello_cmake"],
    cache_entries = {
        "CMAKE_BUILD_TYPE": "Release",
    },
    visibility = ["//visibility:public"],
)
