load("@eros_forge//bazel:cmake_conan_forge.bzl", "cmake_conan_forge")

cmake_conan_forge(
    name = "hello_opencv",
    conanfile = "conanfile.txt",
    cmake_lists = "CMakeLists.txt",
    srcs = [
        "main.cpp",
    ],
    target_name = "hello_opencv",
    visibility = ["//visibility:public"],
)

cmake_conan_forge(
    name = "bench_harris",
    conanfile = "conanfile.txt",
    cmake_lists = "CMakeLists.txt",
    srcs = [
        "bench_harris.cpp",
    ],
    target_name = "bench_harris",
    visibility = ["//visibility:public"],
)
